### ISSUE TITLE
Use of Promises instead of Tasks

### ISSUE THREAD

**Issue by CheloXL** [erik-kallen/SaltarelleCompiler#382]
It would be nice if instead of the Task class you can make use of the native Promise class. 

The only issue with that is that Promises are greedy (so, awaiting a Promise<Promise<int>> would lead to the int result and not, as you can expect in c#, to a Promise<int>).

**Comment by erik-kallen** [comment]
There is a promise class in the runtime, and you can use ```Task.FromPromise``` to use it with async.

If you have a better idea of how to perform this interop, please share; the current model is the best I could think of but I might very likely have overlooked some possibility.

**Comment by CheloXL** [comment]
Yes, I'm aware of that. I was thinking in completely replacing the Task class. You don't really need one for async to work. Any class with a GetAwaiter will do. You can add that method to the Promise class (and hide it from VS with Browsable(false), for example) because it is just for the compiler to work.

You would also need to change your IPromise/Promise definitions, something like:
```c#
public interface IThenable<out T> {
	IThenable<TR> then<TR>(Func<T, IThenable<TR>> onFulfill = null, Func<Exception, IThenable<TR>> onReject = null);
	IThenable<TR> then<TR>(Func<T, TR> onFulfill = null, Func<Exception, IThenable<TR>> onReject = null);
	IThenable<TR> then<TR>(Func<T, IThenable<TR>> onFulfill = null, Func<Exception, TR> onReject = null);
	IThenable<TR> then<TR>(Func<T, TR> onFulfill = null, Func<TR> onReject = null);

	/// <summary>
	/// Sugar for promise.then(undefined, onRejected)
	/// </summary>
	/// <typeparam name="TR"></typeparam>
	/// <param name="onReject">called when/if "promise" rejects</param>
	/// <returns></returns>
	IThenable<TR> @catch<TR>(Func<Exception, IThenable<TR>> onReject);

	/// <summary>
	/// Sugar for promise.then(undefined, onRejected)
	/// </summary>
	/// <typeparam name="TR"></typeparam>
	/// <param name="onReject">called when/if "promise" rejects</param>
	/// <returns></returns>
	IThenable<TR> @catch<TR>(Func<Exception, TR> onReject);
}
```
And of course adjust the state machine to use promises. But that would let you later remove the state machine altogether and use generator functions and "yield" instead of the state machine (in ES6).

Or you can do that now and if you target Es5, you can run the generated code through 6to5 (that already convert generators to state machines), leaving you free to not do that yourself.

**Comment by erik-kallen** [comment]
I want to be source compatible with .net, so that is not an option.

**Comment by nippur72** [comment]
If you are still interested in this issue, I'm working on a [Q](https://github.com/kriskowal/q) implementation of promises that are compatible with `await` / `async`.

It's more or less like this:
```C#
public async void MyFunc()
{
	string s = await (Task<string>) DoSomething();		
	Console.WriteLine(s);		
}

public static Future DoSomething()
{
	Completer compl = new Completer();
		
	Window.SetTimeout(()=>{			
		compl.Resolve("resolved!");
	},3000);

	return compl.Future;
} 
```
(Where `Completer`/`Future` are alternate names for `Deferred`/`Promise`).

Unfortunately the cast to `(Task<string>)` is needed despite there is an implicit operator defined on `Future`:
```C#
string s = await (Task<string>) DoSomething();
// but there is: public static implicit operator Task(Future F) { ...} 		
```
Is guess it's a C# compiler bug, right?

**Comment by erik-kallen** [comment]
@nippur72 async/await doesn't work on Tasks, it works on any type that has a method (or extension method) called GetAwaiter. So if you define a method called GetAwaiter on your Future class you will be able to use that type with await.

**Comment by nippur72** [comment]
ok, many thanks for pointing me that! For some reason I believed async/await worked only with Tasks. 

Now I've rewritten everything without using Tasks at all, and the above mentioned cast is no longer needed.

I have to say I prefer a way lot more JavaScript's promise style than the C# one's, so it's a big relief to be able "Futures" directly. 

If I manage to clean the mess from my code, I'll publish a [Q](https://github.com/kriskowal/q) metadata library for Saltarelle.

**Comment by nippur72** [comment]
Here's there repo: [nippur72/Saltarelle.Q](https://github.com/nippur72/Saltarelle.Q/)
