### ISSUE TITLE
how to access compiled js variable from other .js files

### ISSUE THREAD

**Issue by lepptin2** [erik-kallen/SaltarelleCompiler#386]
hi,
is that possible to access any variables which written in C# from outside js file.

example 
write C# code like this and compile it 

public class MyClassName
    {
        public List<string> MyStringList { get; set; }

        public MyClassName() 
        {
            this.MyStringList = new List<string>();
        }

        public void MyMethod() 
        {
            this.MyStringList.Add("Sample String added");
        }
    }

How can I access "MyStringList" variable and get items from other .js file

**Comment by erik-kallen** [comment]
To set the name of the variable in the generated script, use ```[ScriptName]``` (or ```[PreserveName]```).

**Comment by lepptin2** [comment]
maybe I can not tell
I try to access "MyStringListField" property from any other external .js file like mycustom.js 
How can I access, how can I get this variable ? 

![1](https://cloud.githubusercontent.com/assets/4671844/6263847/f8cbe104-b825-11e4-9f4b-67e305838af4.png)


![3](https://cloud.githubusercontent.com/assets/4671844/6263831/c8231220-b825-11e4-9f35-8ca8b586b2dd.png)

**Comment by erik-kallen** [comment]
I do not understand your question. In the other file you could do

```
var x = new Sinerji.MyClassName();
var theList = x.get_MyStringList(); // preferrably
// var theList = x.$1$MyStringListField; should preferrably not be used.
```

you can also use ```[IntrinsicProperty]``` on the ```MyStringList``` property and then you access it as

```
var x = new Sinerji.MyClassName();
var theList = x.myStringList;
```

I do not understand your question.

**Comment by lepptin2** [comment]
I edit my question now and I add some screenshots. 
Could you please help me
thank you for your patience

![1](https://cloud.githubusercontent.com/assets/4671844/6264514/559e778c-b82d-11e4-827e-7430eb3f50e7.png)

![2](https://cloud.githubusercontent.com/assets/4671844/6264518/5a4e6f9e-b82d-11e4-9394-6b34d81376e9.png)

![3](https://cloud.githubusercontent.com/assets/4671844/6264519/5f1548ea-b82d-11e4-948b-31d460b5594c.png)

![4](https://cloud.githubusercontent.com/assets/4671844/6264523/63ac039e-b82d-11e4-9359-4d611db1ca36.png)

![5](https://cloud.githubusercontent.com/assets/4671844/6264527/6985eb5e-b82d-11e4-8357-4bc3c8e4ba47.png)

![6](https://cloud.githubusercontent.com/assets/4671844/6264529/6d415968-b82d-11e4-9be2-bfaeffb0767e.png)

**Comment by erik-kallen** [comment]
Your question is not really related to C# to JS compilation. I think you need to look for a JS tutorial.

(the answer, I think, to your question is)

```
$(document).ready(function() {
    var x = new Sinerji.MyTestClass();
    var theList = x.get_MyStringList();
});
```
