### ISSUE TITLE
C# if (null == this.MyEvent) throws exception in ss.staticEquals

### ISSUE THREAD

**Issue by ad-tab** [erik-kallen/SaltarelleCompiler#394]
for an if comparison of a delegate where null is the first value - e.g. if (null == this.MyEvent) { }
the output JavaScript is if (ss.staticEquals(null, this.$1$MyEvent))
and throws an exception because null is the first parameter to staticEquals.

In CoreLib\Delegate.cs, I found:
		[InlineCode("{$System.Script}.staticEquals({a}, {b})")]
		public static bool operator==(Delegate a, Delegate b) {
			return false;
		}

And staticEquals throws an exception if (a) is null:

ss.staticEquals = function ss$staticEquals(a, b) {
    if (!ss.isValue(a))
        throw new ss_NullReferenceException('Object is null');
...
};

It seems that instead, when a is null, staticEquals could test that b is also null.

E.g.
  // if either parameter is null, then both must be null
  if (!ss.IsValue(a)  || !ss.IsValue(b))
      return ss.IsNullOrUndefined(a) && ss.IsNullOrUndefined(b);
 ...

**Comment by jon-hall** [comment]
Not sure what version, or branch, of Saltarelle you're using but ss.staticEquals in the master branch doesn't look like that - https://github.com/erik-kallen/SaltarelleCompiler/blob/master/Runtime/CoreLib.Script/mscorlib.js#L171 (and a blame indicates it never did, though it might have been moved around).  It might just be that you need to update to a more recent version where this issue has been fixed or possibly just reinstall the nuget.

**Comment by ad-tab** [comment]
Thanks and sorry for the bother, it's a problem on our end.
