### ISSUE TITLE
Explicit interface implementation not working as expected

### ISSUE THREAD

**Issue by jon-hall** [erik-kallen/SaltarelleCompiler#395]
While trying to use the inline code attribute for an explicitly implemented interface member I found that Saltarelle resolves the member as being defined by the interface rather than the implementing class, resulting in it never outputting the inline code defined in the concrete class (I came across this trying to explicitly implement members of `ICollection<T>`), a simplified example of the C# is below:

    interface IFoo
    {
    	string Bar(int x);
    }
    
    class Foo : IFoo
    {
    	[InlineCode("{this}.doInlineCode({x})")]
    	string IFoo.Bar(int x)
    	{
    		return null;
    	}
    }
    
    public class Program
    {
    	public static void Main()
    	{
    		IFoo f = new Foo();
    		Console.WriteLine(f.Bar(5));
    	}
    }

And the Javascript this produces (within the Main() method) looks like this:

    var f = new $Saltarelle_Explicit_Interface_Bug_$Foo();
    console.log(f.$bar(5));  // This line should be 'console.log(f.doInlineCode(5));'

I spent a while trying to debug the compiler and figure out how the issue might be rectified without much luck, it seems that the compile-time resolution by NRefactory determines the declaring type of the member (`f.Bar(5)`) to be the interface and that then sets in stone the Javascript that gets produced.

I confirmed the same issue is also present in an up-to-date build of the Roslyn branch.

I was wondering if you can comment on whether you believe this can be fixed, and if you have any suggestions as to what that might entail, that'd also be hugely helpful.

**Comment by erik-kallen** [comment]
This won't be changed in v2, and I am not sure if it can even be changed in the Roslyn-based v3, as I don't think Roslyn will ever return any information for non-public methods (which explicit interface implementations are) in other assemblies.

I am also not sure if this is an important feature. If you go through the work of creating special inline code for a method, why do you not want that method to be exposed in the class's public contract?

**Comment by jon-hall** [comment]
I agree that you probably do want to expose such methods, and will revise my code as such.

Though, on reflection, this issue isn't really confined to explicit interface implementations - any implementations of interface members become 'hidden' when an instance of the class is held in a field or variable typed as the interface, e.g.

    class Foo: IFoo {
        [InlineCode("{this}.doInlineCode({x})")]
        public string Bar(int x) {}
    }

    class Baz {
        IFoo i;
        Foo f;
    
        public void Test() {
            i.Bar(5);  // Errors due to no method '$bar' being present (generated code: "i.$bar(5);")
            f.Bar(5); // Works as expected (generated code: "f.doInlineCode(5);")
        }
    }

This creates a requirement to cast to the desired concrete type (`((Foo)i).Bar(5)` would work fine in the example above) to safely call through to the actual implementations in these scenarios (which will rarely be possible when typing something as an interface).

However, I realise this is a corner case (inline code used in combination with interfaces), and (as I suspected) it's probably not a simple one to put in a fix for, so I'm happy to close out this issue if you'd like.  Cheers for getting back to me on it and I'll hopefully be able to work around the issue where it does arise.

**Comment by erik-kallen** [comment]
When you specify inline code on any method implementing an interface member it is your responsibility to ensure that the call works when invoked through the interface as well.

This used to be an error in earlier versions, but it is handy to do it for example to avoid an unnecessary type check in ```List<T>.Add```.

We could potentially report an error when an explicit implementation has an InlineCodeAttribute, since this will never (as of my understanding) produce any sensible behaviour.

**Comment by jon-hall** [comment]
The use case I had, which may be considered valid, was attempting to implement `ICollection<KeyValuePair<TKey, TValue>>` on `JsDictionary<TKey, TValue>` in order to allow collection initialisation to work (as well as providing a richer API to `JsDictionary`).  Because `JsDictionary` only exists as a plain object in the resulting Javascript, the interface method implementations must be done using `InlineCode`.

This then produces an error should anyone store a `JsDictionary<K,V>` in an `ICollection<KeyValuePair<K,V>>` property and call `.Contains(...)` on it, as it utilises the implementation defined on `ICollection<T>`, which cannot operate on a Javascript object.

Due to this, it doesn't seem possible to safely implement `IEnumerable<T>`/`ICollection<T>` on `JsDictionary<K,V>` as far as I can tell.

**Comment by erik-kallen** [comment]
Making JsDictionary not implement the dictionary interfaces is a conscious design decision on my end due to exactly the issues you are running into.

Usually when you are using interface implementations you don't know the actual type of the object, that is kind of the point with interfaces.

In order to get dictionary initializers to work on JsDictionary, it might be possible to have that class implementing the non-generic IEnumerable (which is non-scriptable anyway and only exists for source compatibility and because that interface is required for collection initializers to work at all) and create a public Add method (which needs not implement any interface member) that has an inline code implementation.

**Comment by jon-hall** [comment]
Yeah, figured this might be related to why it doesn't already implement that interface.  Will close out this issue and take a crack at it the way you suggested, hopefully that will get the result I'm after.  Cheers for taking the time to get back to me on all this, much appreciated.
