### ISSUE TITLE
string equality operator

### ISSUE THREAD

**Issue by m5x** [erik-kallen/SaltarelleCompiler#418]
I am surprised that nobody has brought it up yet so if I overlooked something I apologize in advance. I noticed that string comparison using equality operator (==) generates reference equality comparison instead of comparing by value like .NET does. It would be great if it worked the same. It's quite a gotcha especially to people like me who are used to compare strings exclusively this way and are prone to sooner or later put it in Saltarelle project as well without realizing it behaves differently.

**Comment by erik-kallen** [comment]
How do you mean? 

    string s1 = "abcd";
    string s2 = "efgh";
    bool b = s1 == s2;

should generate

    var s1 = 'abcd';
    var s2 = 'efgh;
    var b = s1 == s2;

which (AFAIK) should be semantically equivalent.

**Comment by m5x** [comment]
It does for you? For me it generates this:

`var s1 = 'abcd';
var s2 = 'efgh';
var b = ss.referenceEquals(s1, s2);`

I am using version 2.6.2, maybe it was changed later?

**Comment by erik-kallen** [comment]
Yes, that's right, I forgot. The reason for that is that null and undefined should be treated equivalently. referenceEquals should do an ===, though.

**Comment by m5x** [comment]
I'm not sure I understand. Does it mean you will change it to behave the same as in .NET or it is not possible for some reason?

**Comment by erik-kallen** [comment]
Is it broken? Or is it just that it looks wrong? Doesn't `'a' + 'b' == 'ab'` return true?

**Comment by m5x** [comment]
It does indeed. I must have mistakenly blame referenceEquals instead of my own code because now that I try it it compares strings by value. I must have let myself be mislead by the name of the comparison method. As long as it works the same as in .NET I have no problem with that. I apologize for not checking twice before posting.
