### ISSUE TITLE
Task.FromPromise resolved result is 1-element array

### ISSUE THREAD

**Issue by nippur72** [erik-kallen/SaltarelleCompiler#422]
I have a `IPromise` that I turn into a `Task` with `Task.FromPromise()` but the resolved promise result is wrongly returned as an 1-element array.

E.g. if I have `deferred.resolve("ok");` I later get `["ok"]` instead of `"ok"`.

Is this behavior correct or is it a bug?

IMO, it's because of this code in mscorlib:

```JavaScript
ss_Task.fromPromise = function Task$fromPromise(p, f) {
	var tcs = new ss_TaskCompletionSource();
	if (typeof(f) === 'number')
		f = (function(i) { return function() { return arguments[i >= 0 ? i : (arguments.length + i)]; }; })(f);
	else if (typeof(f) !== 'function')
		f = function() { return Array.prototype.slice.call(arguments, 0); };
```
last line should be:
```JavaScript
		f = function() { return arguments[0]; };
```
I ask because I am not sure, I'm not familiar with the code, in case I can write a PR that fix it.

(All this is related with #382, I'm attempting to make `async`/`await` work with promises and still have compatibility with .NET Tasks)

**Comment by erik-kallen** [comment]
```Task.FromPromise``` returns a ```Task<object[]>```, so the behavior is by design. If we are going to change it, how would we handle promises that return multiple values?

**Comment by nippur72** [comment]
oops hadn't noticed the `Task<object[]>` signature, anyway doesnt mind much because I am rewriting it without using tasks at all (see my other comments)
